name: ci
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" | tee -a ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: make docker-build IMAGE_TAG=${IMAGE_TAG:-latest}

      - name: Login to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        if: startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/main'
        run: docker push $(make show-image-full-name IMAGE_TAG=${IMAGE_TAG:-latest})
